package org.victorrobotics.devilscoutserver;

import static io.javalin.apibuilder.ApiBuilder.delete;
import static io.javalin.apibuilder.ApiBuilder.get;
import static io.javalin.apibuilder.ApiBuilder.patch;
import static io.javalin.apibuilder.ApiBuilder.path;
import static io.javalin.apibuilder.ApiBuilder.post;
import static io.javalin.apibuilder.ApiBuilder.put;

import org.victorrobotics.devilscoutserver.cache.EventInfoCache;
import org.victorrobotics.devilscoutserver.controller.Controller;
import org.victorrobotics.devilscoutserver.controller.EventInfoController;
import org.victorrobotics.devilscoutserver.controller.QuestionsController;
import org.victorrobotics.devilscoutserver.controller.SessionController;
import org.victorrobotics.devilscoutserver.controller.UserController;
import org.victorrobotics.devilscoutserver.database.SessionDB;
import org.victorrobotics.devilscoutserver.database.TeamConfigDB;
import org.victorrobotics.devilscoutserver.database.UserDB;

import io.javalin.Javalin;
import io.javalin.http.Handler;
import io.javalin.openapi.ApiKeyAuth;
import io.javalin.openapi.plugin.OpenApiPlugin;
import io.javalin.openapi.plugin.OpenApiPluginConfiguration;
import io.javalin.openapi.plugin.SecurityComponentConfiguration;
import io.javalin.openapi.plugin.swagger.SwaggerConfiguration;
import io.javalin.openapi.plugin.swagger.SwaggerPlugin;

public class Server {
  private static final Handler UNIMPLEMENTED = ctx -> ctx.result("UNIMPLEMENTED");

  private static final String API_DESCRIPTION =
      """
          ## Overview
          Information and statistics on FRC competitions, pooled together by all registered teams.
          ## Authentication
          All endpoints (except for `/login` and `/auth`) require a session key to be passed in the header
          `%s`. This will be generated by the server upon successful authentication.
          """.formatted(Controller.SESSION_HEADER);
  private static final String TAGS_SORTER     = """
      /* INJECTED */ (a,b) => {
        const tagOrder = ['Authentication', 'Questions', 'Teams', 'Users'];
        return tagOrder.indexOf(a) - tagOrder.indexOf(b);
      }
      """;
  // Hack to inject directly instead of serving file
  private static final String REMOVE_TOP_BAR = """
      '></script><script>
        /* INJECTED */
        let onLoad = window.onload;
        window.onload = function() {
          onLoad();
          let topbar = document.getElementsByClassName('topbar')[0];
          topbar.parentNode.removeChild(topbar);
        };
      </script><script src='""";

  private final Javalin javalin;

  public Server() {
    javalin = Javalin.create(config -> {
      config.http.prefer405over404 = true;

      // @format:off
      config.plugins.register(new OpenApiPlugin(
        new OpenApiPluginConfiguration()
          .withDocumentationPath("/openapi/json")
          .withDefinitionConfiguration((version, definition) -> definition
            .withOpenApiInfo(openApiInfo -> {
              openApiInfo.setTitle("DevilScout Server");
              openApiInfo.setVersion("alpha");
              openApiInfo.setDescription(API_DESCRIPTION);
            })
            .withSecurity(new SecurityComponentConfiguration()
              .withSecurityScheme("Session", new ApiKeyAuth() {
                @Override
                public String getName() {
                  return Controller.SESSION_HEADER;
                }
              })
            )
          )
        )
      );
      // @format:on

      SwaggerConfiguration uiConfig = new SwaggerConfiguration();
      uiConfig.setTitle("DevilScout Server API");
      uiConfig.setDocumentationPath("/openapi/json");
      uiConfig.setUiPath("/openapi/ui");
      uiConfig.setTagsSorter(TAGS_SORTER);
      uiConfig.injectJavaScript(REMOVE_TOP_BAR);
      config.plugins.register(new SwaggerPlugin(uiConfig));
    });

    javalin.routes(() -> {
      post("login", SessionController::login);
      post("auth", SessionController::auth);
      delete("logout", SessionController::logout);

      get("event_info", EventInfoController::eventInfo);

      path("questions", () -> {
        get("match", QuestionsController::matchQuestions);
        get("pit", QuestionsController::pitQuestions);
        get("drive_team", QuestionsController::driveTeamQuestions);
      });

      path("scout", () -> {
        post("match", UNIMPLEMENTED); // upload a match scouting record
        post("pit", UNIMPLEMENTED); // upload a pit scouting record
        post("drive_team", UNIMPLEMENTED); // upload a post-match record (ADMIN)
      });

      path("analysis", () -> {
        get("teams", UNIMPLEMENTED); // summaries by team at current event
        post("simulation", UNIMPLEMENTED); // request match simulation
        post("optimization", UNIMPLEMENTED); // request alliance optimization
      });

      path("teams", () -> {
        get(UNIMPLEMENTED); // get registered teams (SUDO)
        put(UNIMPLEMENTED); // register new team (SUDO)
        delete(UNIMPLEMENTED); // unregister team (SUDO)
        patch(UNIMPLEMENTED); // update team info (ADMIN/SUDO)

        path("{team}", () -> {
          get("users", UserController::usersOnTeam);
        });
      });

      path("users", () -> {
        get(UserController::allUsers);
        put(UserController::registerUser);

        path("{id}", () -> {
          get(UserController::getUser);
          delete(UserController::deleteUser);
          patch(UserController::editUser);
        });
      });

      get("dev_session", SessionController::generateDevSession);
    });
  }

  public void start() {
    javalin.start(8000);
  }

  public void stop() {
    javalin.stop();
  }

  public static void main(String... args) {
    Controller.setUserDB(new UserDB());
    Controller.setSessionDB(new SessionDB());
    Controller.setTeamDB(new TeamConfigDB());

    Controller.setEventInfoCache(new EventInfoCache());

    Controller.loadAll();
    Server server = new Server();
    server.start();
  }
}
