name: Gradle Build
on: [push]
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
    - name: Generate dependency graph
      uses: gradle/actions/dependency-submission@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build
      run: ./gradlew build --no-daemon
